#
#
#
#

- hosts: localhost

  tasks:

    - name: Setting up Security/Firewall group
      ec2_group:
         name: Spider_tutorial_Security_group
         description: Rules allowing traffic on port 22 and 80
         region: us-west-2
         rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
         rules_egress: 
          - proto: all
            cidr_ip: 0.0.0.0/0
    - name: Provision an EC2 Insatance
      ec2:
         key_name: darshanaws
         region: us-west-2
         instance_type: t2.micro
         image: ami-0def3275
         wait: yes
         wait_timeout: 500
         count: 1
         instance_tags: 
           Name: spidertutorial_server
           Owner: Darshan
         monitoring: no
         vpc_subnet_id: subnet-04eb6363
         assign_public_ip: yes
         group: Spider_tutorial_Security_group
      register: ec2_out
    - name: Install Apache Webserver
      apt: name=apache2 state=installed
      notify:
      - restart apache2
    - name: Ensure apache is running and enabled it under boot
      service: name=httpd state=restarted enabled=yes







#    - name: Wait for ssh to come up
#      wait_for: host={{ item.public_dns_name }} port=22 delay=60 timeout=320 state=started
#      with_items: '{{ec2_out.instances}}'
